spring:
  application:
    name: gateway
  cloud:
    services:
      registrationMethod: route
security:
  basic:
    enabled: false
zuul:
  routes:
    resources:
      path: /resources/**
      url : http://hello-service.apps.bigdata.intraorange/
ribbon:
  IsSecure: true
---
spring:
  profiles: dev
